### DISCUSSION TITLE
u32 values

### DISCUSSION THREAD

**Discussion by andyp-79** [nliaudat/esp_canbus#15] [General]
Trying to figure out how to retrieve U32 based high/low values such as these datapoints for a heat pump:

![image](https://github.com/nliaudat/esp_canbus/assets/6251451/f9823ebc-98fb-476b-8d2a-01fd8fdc7990)

I know the data is reported to the displays on the unit, but I don't see them going over the CAN bus. I can only  see the GET request data going over the wire:

```
19:22:57	[I]	[tt:230]	
[GET] Data: 0x01400a0159e1
```

Could it be that the response neither fit the SENSOR nor TEXTSENSOR format? Has anyone successfully read u32 based datapoints in an actual environment?

**Comment by nliaudat** [comment]
It's not implemented now as U32 and S32 values are only readable and are a very small part of all Toptronic datapoints. 

In fact the canbus communication of hoval devices is a mix of canbus and modbus.

The U32 and S32 values are splited in 2 messages over canbus if my memory is good. 
They should be regrouped to get the raw value. 

I have no time to support you further for now.  Very sorry.

Perhaps @abichinger could help you

Regards

**Comment by nliaudat** [comment]
You can open a discussion. 
I mean is not a real issue but more a feature request.
You can close it if you agree

**Comment by andyp-79** [comment]
Happy to change this to a feature request. I could also help with contributing an implementation for the split messages, if you happen to know how to identify the messages that belong together. I’ve been unable to identify these, despite having a few wireshark dumps of the can bus messages. If you could share what to look for, I could probably put this together.

**Reply by nliaudat** [reply]
Sorry, there is no way to convert issue to feature request actually. 
I tranfert it to discussion. 
I have an HV (homevent). I'll do some tests on capturing the U32 values if I found time too. 

In the meanwhile, perhaps you can find responses in [https://github.com/chrishrb/hoval-gateway](https://github.com/wladwnt/CAN-Gateway) which have a very good understanding of Hoval canbus protocol. 

I'll try to do it asap, but I am very busy actually.

Regards and welcome to that project.

**Comment by nliaudat** [comment]
I have made some test on my homevent with U32 values by activating :

```
sensor:
- platform: toptronic
  name: Maint_ctr_value low
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 50
  function_number: 0
  datapoint: 20037
  id: HV_50_0_20037
  type: U32
```

In the first analysis of code, the U32 value seems handled correctly. 

There is no trafic on canbus on that datapoint. 
Perhaps the problem is only to make a good request as the request code (0x40) was reversed engineered and perhaps do not fit U32 value.

**Reply by nliaudat** [reply]
from hoval documentation : 
**Address of the data point**
--
A data point can have several register addresses depending on the TypeName:
Data points with TypeName S8,U8,S16,U16,List need only one address.
Four-byte or eight-byte data points (TypeName: U32,S32,S64)
are divided to 2 or 4 Modbus data points. These are marked with a
"high" for highbytes and "low" for lowbytes marked."

**Reply by nliaudat** [reply]
from https://raw.githubusercontent.com/wladwnt/CAN-Gateway/master/Operating_manual.pdf p42

    Basis address = (order number-1)*10
    Parameters with data types U32 or S32 will get two addresses, meaning will be mapped to two
    registers in terms of Modbus. The basis address above will address the two highest bytes (also will
    include the most significant bit), the next address (=basis address + 1) will address the two lowest
    bytes (also will include the last significant bit). For example, if a parameter number 5 has type U32,
    then it will get addresses 40 and 41.

**Comment by abichinger** [comment]
@andresp do you receive a value with the following sensor?
```yaml
sensor:
- platform: toptronic
  name: Eletrical energy low
  device_type: WEZ
  device_addr: ${TT_WEZ_addr}
  function_group: 10
  function_number: 1
  datapoint: 23009
  id: WEZ_10_1_23009
  type: U32
  accuracy_decimals: 0
  filters:
  - multiply: 1
```

**Reply by nliaudat** [reply]
Do not work with : 

      - platform: toptronic
        name: Maint_ctr_value low
        device_type: HV
        device_addr: ${TT_HV_addr}
        function_group: 50
        function_number: 0
        datapoint: 20037
        id: HV_50_0_20037
        type: U32
        accuracy_decimals: 0
        filters:
        - multiply: 1
  
  I've tested with type: U8 and U16 instead of U32 to catch the 1st part only of the registered message with no luck.

**Reply by nliaudat** [reply]
And with multiply: 0.001 ?

```yaml
sensor:
- platform: toptronic
  name: Eletrical energy low
  device_type: WEZ
  device_addr: ${TT_WEZ_addr}
  function_group: 10
  function_number: 1
  datapoint: 23009
  id: WEZ_10_1_23009
  type: U32
  filters:
  - multiply: 0.001
```
