### DISCUSSION TITLE
esphome canbus

### DISCUSSION THREAD

**Discussion by nliaudat** [nliaudat/esp_canbus#3] [firmware]
replace issue https://github.com/nliaudat/esp_canbus/issues/2

**Comment by bagges** [comment]
I just built my PCB. I will try to gather some infos this week.

**Comment by bagges** [comment]
Decoded first messages. Example:


**Feuchte Sollwert**

> 
> [23:53:09][D][canbus:067]: received can message (#1) extended can_id=0x1fe04208 size=6
> [23:53:09][V][canbus:077]:   can_message.data[0]=01
> [23:53:09][V][canbus:077]:   can_message.data[1]=40
> [23:53:09][V][canbus:077]:   can_message.data[2]=32
> [23:53:09][V][canbus:077]:   can_message.data[3]=00
> [23:53:09][V][canbus:077]:   can_message.data[4]=9e
> [23:53:09][V][canbus:077]:   can_message.data[5]=ef
> [23:53:09][D][canbus:067]: received can message (#2) extended can_id=0x1fd047ff size=7
> [23:53:09][V][canbus:077]:   can_message.data[0]=01
> [23:53:09][V][canbus:077]:   can_message.data[1]=42
> [23:53:09][V][canbus:077]:   can_message.data[2]=32
> [23:53:09][V][canbus:077]:   can_message.data[3]=00
> [23:53:09][V][canbus:077]:   can_message.data[4]=9e
> [23:53:09][V][canbus:077]:   can_message.data[5]=ef
> [23:53:09][V][canbus:077]:   can_message.data[6]=32
> 

**can_id=0x1fe04208**

- 1f-> 31 messageid
- e0-> 224 priority
- 42 -> 66 ? device type
- 08 -> 8 device id

**CAN message**

- 01 len
- 40/42 OP Request/Answer
- 32 FN Group 50
- 00 FN Number
- 9eef -> Datapoint 40687
- 32 -> Value 50 %

**Comment by nliaudat** [comment]
Perhaps it could help : 
[can-gateway-datapoints.csv](https://github.com/nliaudat/esp_canbus/files/11680028/can-gateway-datapoints.csv)

**Comment by bagges** [comment]
![image](https://github.com/nliaudat/esp_canbus/assets/2102004/e3a704fb-20f9-43ce-8221-f65eb12902ad)

I got the first sensors working. Not production ready, but at least something.

```
canbus:
  - platform: esp32_can
    tx_pin: GPIO5
    rx_pin: GPIO4
    can_id: 8
    bit_rate: 50kbps
    on_frame:
    - can_id: 0x1f
      can_id_mask: 0x0000001f
      use_extended_id: true
      then:
      - lambda: |-
         if(x.size() > 6) {
            uint32_t myInt1 = x[5] + (x[4] << 8);
            switch(myInt1) {
                case 38606:
                    id(lueftungsmodulation).publish_state((uint8_t)x[6]);
                    break;
                case 40687:
                    id(feuchtesollwert).publish_state((uint8_t)x[6]);
                    break;
                case 0:
                    id(temperaturaussen).publish_state(((uint16_t)x[6]) / 10);
                    break;
                case 37602:
                    id(temperaturabluft).publish_state(((uint16_t)x[6]) / 10);
                    break;
            }
         }
         
sensor:
  - platform: template
    name: "Lüftungsmodulation"
    id: lueftungsmodulation
  - platform: template
    name: "Feuchte Sollwert"
    id: feuchtesollwert
  - platform: template
    name: "Temperatur Aussenluft"
    id: temperaturaussen
  - platform: template
    name: "Temperatur Abluft"
    id: temperaturabluft
```

**Comment by nliaudat** [comment]
Great !

I'll try to generate a sensor list from the datapoints with substitutions for translation like that : 

```
substitutions:
### English
# use concatenation of UnitName, FunctionGroup, FunctionNumber, DatapointId as identifier
  HV-50-0-40687: Humidity set value

sensor:
  - platform: template
    name: ${HV-50-0-40687}
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    device_class: "humidity"
    state_class: "measurement"
    accuracy_decimals: 0
    #filters:
     # - multiply: 0.1 ## for S16 TypeName
    #### only for reference
    #UnitName: HV
    #FunctionGroup: Ventilation
    #commentary : Humidity setpoint (maximum rel. air humidity set on the operator terminal)
    #TypeName: U8 
    #writable : yes
    #min : 30
    #max : 65
    id: HV-50-0-40687

canbus: 
...
          case 40687:
                    id(HV-50-0-40687).publish_state((uint8_t)x[6]);

```

**Comment by nliaudat** [comment]
New processing data script : https://github.com/nliaudat/esp_canbus/tree/main/esphome/hoval_data_processing

- xls-parser-substitutions.py is working
- xls-parser-sensor.py needs more job

**Comment by bagges** [comment]
Updated some code. S16 values now working, but outside temp value flips between 0 and real value...
```
canbus:
  - platform: esp32_can
    tx_pin: GPIO5
    rx_pin: GPIO4
    can_id: 8
    bit_rate: 50kbps
    on_frame:
    - can_id: 0x1f
      can_id_mask: 0x0000001f
      use_extended_id: true
      then:
      - lambda: |-
         if(x.size() > 6) {
            uint32_t myInt1 = x[5] + (x[4] << 8);
            switch(myInt1) {
                case 38606:
                    id(lueftungsmodulation).publish_state((uint8_t)x[6]);
                    break;
                case 40687:
                    id(feuchtesollwert).publish_state((uint8_t)x[6]);
                    break;
                case 37600:
                    id(feuchtigkeitabluft).publish_state((uint8_t)x[6]);
                    break;
            }
            if(x.size() > 7) {
                int temp = (int16_t)(x[6] << 8) + x[7];
                switch(myInt1) {
                    case 0:
                        id(temperaturaussen).publish_state(temp);
                        break;
                    case 37602:
                        id(temperaturabluft).publish_state(temp);
                        break;
                    }
            }
         }
         
sensor:
  - platform: template
    name: "Lüftungsmodulation"
    id: lueftungsmodulation
  - platform: template
    name: "Feuchte Sollwert"
    id: feuchtesollwert
  - platform: template
    name: "Temperatur Aussenluft"
    id: temperaturaussen
    filters:
      - multiply: 0.1
  - platform: template
    name: "Temperatur Abluft"
    id: temperaturabluft
    filters:
      - multiply: 0.1
  - platform: template
    name: "Feuchtigkeit Abluft"
    id: feuchtigkeitabluft
```

**Comment by nliaudat** [comment]
I have finished the sensors and translation part (using substitutions). I need to make the script to generate canbus configuration. 

The code posted in https://github.com/nliaudat/esp_canbus/tree/main/esphome has only HV (homevent) sensors but the scripts can generate all the devices.

**Reply by nliaudat** [reply]
canbus script done. Can you test the code generated with ( https://github.com/nliaudat/esp_canbus/blob/main/esphome/canbus.yaml)
`esphome run config.yaml`

**Comment by bagges** [comment]
Some remarks:

- IMO the configuration is a bit too complex.
- web_server is missing
- esp keeps rebooting and my Hoval TopTronic shows CANBUS Errors
- Humidity and Outside Temp does not work at all
- I have no VOC sensors, so I do not know if they would work.
- Status is wrong, should be 4 but shows 1

![image](https://github.com/nliaudat/esp_canbus/assets/2102004/d04f24c9-f0ce-4b15-a794-775be2727306)

**Reply by nliaudat** [reply]
Sorry if the setup is a bit complex. I tried to make it as generic as possible.

I added the web server enabled by default

For reboots, I think the esp32 is not fast enough or variable overflow.

For the rest, I'm waiting for my board to be able to test

**Reply by nliaudat** [reply]
For the reboots, it's related to https://github.com/esphome/issues/issues/4051.
Setting the log level to INFO should do the trick. 

in board.yaml : 

```
# Enable logging
logger:
  level: INFO
  #baud_rate: 0 #to disable logging via UART
  logs:
    text_sensor : ERROR
    homeassistant.sensor: ERROR
    canbus: INFO
```

**Comment by nliaudat** [comment]
I've seen that modbus works with hoval components. Perhaps, it's the way to go : https://community.home-assistant.io/t/hoval-modbus-uint8/504883

**Comment by bagges** [comment]
I do not see a modbus interface on my homevent.

**Reply by nliaudat** [reply]
modbus tcp/ip. That's the same as canbus interface. 
The main advantage is the easy configuration : 

```
# Hoval
- name: hoval
  type: tcp
  host: 192.168.1.208
  port: 502
  close_comm_on_error: true
  delay: 5
  timeout: 5
  sensors:
    - name: hoval_hv_lueftungsmodulation_normal
      unit_of_measurement: "%"
      slave: 1
      address: 23610
      data_type: uint8
      scale: 1
      precision: 0
      count: 1
      scan_interval: 180
```

**Comment by bagges** [comment]
My homevent does not have a network connection. HV is just connected to a toptronic e. So for me this won't work.

**Reply by nliaudat** [reply]
The H-L and H-L ports of canbus can be read with modbus RX/TX. 
Canbus & modbus TCP are fast the same.
I have to test when I receive my PCB.

**Comment by nliaudat** [comment]
The good news is that I received my board and it's working.

I have issues with "Outside air temp." as the canbus sends 0 every seconds and the real value perhaps 1x per minutes. 
I'll change the code to dismiss 0 values.

**Comment by nliaudat** [comment]
New version is working great ! 
![image](https://github.com/nliaudat/esp_canbus/assets/6782613/d329741a-6da8-4243-93a3-12bda9e088c8)


ps: you have to change to your pin board
```
canbus:
    tx_pin: GPIO22 #GPIO5
    rx_pin: GPIO21 #GPIO4
```

**Comment by bagges** [comment]
Awesome! Will give it a try next week or so.

**Comment by nliaudat** [comment]
canbus on frame is not the good way to go as some sensors do not updates their stats if not requested. 

I've tried to update the "humidity state value" without success, but the sensor need to request (0x40) canbus message as same as update (0x46) .

As sample, if satus ventilation is 5 (cold mode), no temperature is provided

**Comment by nliaudat** [comment]
cannot get the right canbus.send to update value (or request)

if monitoring "Humidity set value" here is the response : 
```

[22:12:22][I][canbus:069]: Humidity set value : Response Hex8:  1 42 32 0 9e ef 32 78
[22:12:22][I][canbus:070]: Humidity set value : Response Hex16: 1 42 32 0 9e ef 32 78 56 ad ba 3f 1c 0 0 0
```

data : message_len = 1, operation = 70 (0x46), function_group = 50 (0x32), function_number = 0 (0x00), datapoint = 40687 (9eef) , value,, end message ? = 0x78

data[1] = 42 for response :

    # """Operations in CAN-Message"""
    # RESPONSE = 0x42
    # GET_REQUEST = 0x40
    # SET_REQUEST = 0x46

I tried a lot of canbus.send messages with 0x46 ( SET_REQUEST ): 

```
select:
  - platform: template
    name: "Debug"
    id: canbus_debug_tag
    optimistic: true
    options:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      - "10"
    set_action:
      then:
          - delay: 500ms
          - if:
              condition:
                - lambda: |-
                    return (id(canbus_debug_tag).state) == "1";
              then:
                - canbus.send: 
                    data: [ 0x1, 0x46, 0x32, 0x00, 0x9e, 0xef, 0x23]
          - if:
              condition:
                - lambda: |-
                    return (id(canbus_debug_tag).state) == "2";
              then:
                - canbus.send: 
                    data: [ 0x46, 0x32, 0x00, 0x9e, 0xef, 0x23]
          - if:
              condition:
                - lambda: |-
                    return (id(canbus_debug_tag).state) == "3";
              then:
                - canbus.send: 
                    data: [ 0x46, 0x32, 0x9e, 0xef, 0x23]
          - if:
              condition:
                - lambda: |-
                    return (id(canbus_debug_tag).state) == "4";
              then:
                - canbus.send: 
                    data: [ 0x46, 0x9e, 0xef, 0x23]
          - if:
              condition:
                - lambda: |-
                    return (id(canbus_debug_tag).state) == "5";
              then:
                - canbus.send: 
                    data: [ 0x9e, 0xef, 0x23]
          - if:
              condition:
                - lambda: |-
                    return (id(canbus_debug_tag).state) == "6";
              then:
                - canbus.send: 
                    data: [ 0x1, 0x46, 0x32, 0x00, 0x9e, 0xef, 0x23]
                    canbus_id: cbus # optional if you only have 1 canbus device
                    can_id: 8 # override the can_id configured in the can bus
                    use_extended_id: true
          - if:
              condition:
                - lambda: |-
                    return (id(canbus_debug_tag).state) == "7";
              then:
                - canbus.send: 
                    data: [ 0x46, 0x32, 0x00, 0x9e, 0xef, 0x23]
                    canbus_id: cbus # optional if you only have 1 canbus device
                    can_id: 8 # override the can_id configured in the can bus
                    use_extended_id: true
          - if:
              condition:
                - lambda: |-
                    return (id(canbus_debug_tag).state) == "8";
              then:
                - canbus.send: 
                    data: [ 0x46, 0x32, 0x9e, 0xef, 0x23]
                    canbus_id: cbus # optional if you only have 1 canbus device
                    can_id: 8 # override the can_id configured in the can bus
                    use_extended_id: true
          - if:
              condition:
                - lambda: |-
                    return (id(canbus_debug_tag).state) == "9";
              then:
                - canbus.send: 
                    data: [ 0x46, 0x9e, 0xef, 0x23]
                    canbus_id: cbus # optional if you only have 1 canbus device
                    can_id: 8 # override the can_id configured in the can bus
                    use_extended_id: true
          - if:
              condition:
                - lambda: |-
                    return (id(canbus_debug_tag).state) == "10";
              then:
                - canbus.send: 
                    data: [ 0x9e, 0xef, 0x23]
                    canbus_id: cbus # optional if you only have 1 canbus device
                    can_id: 8 # override the can_id configured in the can bus
                    use_extended_id: true

```

**Reply by nliaudat** [reply]
@chrishrb can you help for sending good canbus update message ? 
I've studied your code  https://github.com/chrishrb/hoval-gateway/blob/main/gateway/message.py#L72C7-L72C18 but cannot applies it the good way.

**Comment by bagges** [comment]
I think you need to send something like:

`- canbus.send: [ 0x20, 0xE0, 0x0A, 0x08, 0x01, 0x40, 0x32, 0x00, 0x9E, 0xCA ]`

0x20 -> MessageID 32 (should be incrementet for further requests)
0xE0 -> Priority
0x0A -> device type
0x08 -> device id
0x01 -> len
0x40 -> GET Request
0x32 -> fn group
0x00 -> 0
0x9e -> datapoint
0xca -> datapoint

**Reply by nliaudat** [reply]
many thanks ! I'll have a try.

**Reply by nliaudat** [reply]
not easy, 5 days I try to make it works without success. 
I mean esphome canbus implementation is not full feature actually.

**Comment by nliaudat** [comment]
Getting it works ! 

The can ID was not accurate enough : 0x1F => 0x1FE04208

```
                        - canbus.send:
                            canbus_id: cbus
                            can_id: 0x1FE04208
                            data: [0x01, 0x40, 0x32, 0x00, 0x92, 0xE0]
                            use_extended_id: true
```
