### ISSUE TITLE
Add support for active error

### ISSUE THREAD

**Issue by Dieghito72** [nliaudat/esp_canbus#16]
**Is your feature request related to a problem? Please describe.**
I have a HOVAL VMC with only the basic controller, not the TopTronic E controller. So I use an ESP with this component to control and monitor the VMC.
I would like also to monitor error codes from the VMC.

![image](https://github.com/user-attachments/assets/75b2d86c-18f7-46eb-8711-a1788c02640c)

**Describe the solution you'd like**
If I understand well at the moment this is not possible because error info are spread across multiple bytes (15) so there isn't a data type that can contains all the information, so even creating a single sensor containing all the values is not possible.

The idea would be having different sensors (maybe a new sensor type?) were is possible to define start byte:

```YAML
sensor:
- platform: toptronic
  name: Active error 1 appearance timestamp
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 0
  function_number: 0
  datapoint: 29042
  start_byte: 0
  id: HV_0_0_29042
  type: U32
- platform: toptronic
  name: Active error 1 disappear timestamp
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 0
  function_number: 4
  datapoint: 29042
  start_byte: 4
  id: HV_0_0_29042
  type: U32
```
