### ISSUE TITLE
TODO - xls parser : hide sensor if already in inputs

### ISSUE THREAD

**Issue by nliaudat** [nliaudat/esp_canbus#18]
Find a way to set 
`internal: true`
in sensor if it's already on inputs. 

The writable parameter could be the trick. 

in sensors_LANG.yaml
the parameter `internal: true` must be add
```
- platform: toptronic
  name: Normal ventilation modulation
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 50
  function_number: 0
  datapoint: 40651
  id: HV_50_0_40651
  type: U8
  unit_of_measurement: '%'
  **_internal: true_**
```

inputs_LANG.yaml for notes

```
number:
- platform: toptronic
  name: Normal ventilation modulation
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 50
  function_number: 0
  datapoint: 40651
  id: HV_50_0_40651_set
  type: U8
  unit_of_measurement: '%'
  min_value: 15
  max_value: 100
  step: 1
  decimal: 0
```
